model: path/to/model/
enable_wandb_logging: True

wandb_config:
  project: MedGPT
  name: test-run

train_parameters:
  output_dir: path/to/model/save/dir
  max_seq_len: 2048 # Should be <= model's max sequence length
  epochs: 1
  seed: 11

  # Memory
  use_mp: True
  use_activation_checkpointing: True
  use_flash_attention: True

  # Gradient norm clipping
  max_grad_norm: 1
  gradient_accumulation_steps: 8 # Aim for a BS of 128, forumla is: n_dev * batch_size * acc_steps

  # Optimizer
  optimizer:
    lr: 2.0e-5
    weight_decay: 0.1
    betas: [0.9, 0.95]
    eps: 1.0e-5
  
  # Scheduler
  lr_scheduler_type: cosine # TODO: include plataeu
  warmup_ratio: 0.05

  # Checkpointing
  checkpointing_enabled: False # If we should checkpoint model training
  logging_steps: 50  # TODO: change to 500
  save_frequency: 0.25  # TODO: change to 0.25s

dataset:
  ignore_index: -100 # The index used to exclude a token from loss calculation
  eval_bs: 4 # Per device batch size
  train_bs: 4 # Per device batch size
  train_ds: path/to/train/ds
  eval_ds: path/to/eval/ds

dataset_preprocess:
  ignore_index: -100 # The index used to exclude a token from loss calculation
  dataset_format: hf # Or json
  dataset_type: pretrain # or sft
  data_field: text
  packing_type: partial
  add_bos_eos_tokens: True
  from_disk: True
  load_path: path/to/unprocessed/dataset
  split: train
  save_path: path/to/processed/dataset/save